CREATE TABLE IF NOT EXISTS person
(
  id        INTEGER NOT NULL AUTO_INCREMENT,
  login     VARCHAR(255),
  password  VARCHAR(255),
  birthdate DATE,
  PRIMARY KEY (id)
)
 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

ALTER TABLE person AUTO_INCREMENT=1000;
